README.md, docs/Designs/cpp2-parameters.md
- add motivation and tool introduction text
- add few high-level examples
- add cpp2 parameters design doc
=> Readme update

include/vast/Dialect/HighLevel/HighLevelOps.td, include/vast/Translation/CodeGenBuilder.hpp, include/vast/Translation/CodeGenDeclVisitor.hpp, include/vast/Translation/CodeGenStmtVisitor.hpp, include/vast/Translation/CodeGenVisitorBase.hpp, include/vast/Util/Common.hpp, lib/vast/Dialect/HighLevel/HighLevelDialect.cpp, lib/vast/Dialect/HighLevel/HighLevelOps.cpp, lib/vast/Dialect/LowLevel/Transforms/ToLLVM.cpp, test/vast/Dialect/HighLevel/indirect-call-a.c
=> Fix codegen indirect call

include/vast/Translation/CodeGenTypeVisitor.hpp
The changes fix #216 (missing support of BlockPointerTypes). It follows how the `PointerTypes` are getting lowered and binds Pointee and qualifier to a MLIR PointerTypes.
=> Added support for BlockPointerTypes

include/vast/Dialect/Core/TypeTraits.hpp, include/vast/Dialect/Core/Utils.td, include/vast/Dialect/HighLevel/HighLevelOps.td, include/vast/Dialect/HighLevel/HighLevelTypes.hpp, include/vast/Dialect/HighLevel/HighLevelTypes.td, include/vast/Translation/CodeGenStmtVisitor.hpp, test/vast/Dialect/HighLevel/add-a.c, test/vast/Dialect/HighLevel/addfloat-a.c, test/vast/Dialect/HighLevel/divfloat-a.c, test/vast/Dialect/HighLevel/divsigned-a.c, test/vast/Dialect/HighLevel/divunsigned-a.c, test/vast/Dialect/HighLevel/enum-c.c, test/vast/Dialect/HighLevel/mul-a.c, test/vast/Dialect/HighLevel/mulfloat-a.c, test/vast/Dialect/HighLevel/ops-a.c, test/vast/Dialect/HighLevel/ops-h.c, test/vast/Dialect/HighLevel/pointerops-a.c, test/vast/Dialect/HighLevel/remsigned-a.c, test/vast/Dialect/HighLevel/remunsigned-a.c, test/vast/Dialect/HighLevel/sub-a.c, test/vast/Dialect/HighLevel/subfloat-a.c, test/vast/Dialect/HighLevel/typedef-a.c, test/vast/Dialect/HighLevel/typedef-b.c, test/vast/Dialect/HighLevel/typedef-c.c
=> Pointer arithmetic

include/vast/Dialect/HighLevel/HighLevelCF.td, include/vast/Dialect/HighLevel/HighLevelDialect.hpp, include/vast/Translation/CodeGenStmtVisitor.hpp, lib/vast/Dialect/HighLevel/HighLevelOps.cpp, test/vast/Dialect/HighLevel/ternary-a.c
Resolve #231. Would be glad if someone checked if I am implementing the `RegionBranchOpInterface` correctly, as I had to do a bit of digging to figure it out.
=> Add conditional (ternary) operator to hl

include/vast/Dialect/HighLevel/HighLevelTypes.td, include/vast/Translation/CodeGenBuilder.hpp, include/vast/Translation/CodeGenTypeVisitor.hpp
=> Add adjusted type support

include/vast/Dialect/HighLevel/HighLevelOps.td, include/vast/Translation/CodeGen.hpp, include/vast/Translation/CodeGenContext.hpp, include/vast/Translation/CodeGenDeclVisitor.hpp, lib/vast/Dialect/HighLevel/HighLevelOps.cpp
=> Fix multiple function definitions

include/vast/Dialect/HighLevel/HighLevelOps.td, include/vast/Translation/CodeGenStmtVisitor.hpp, test/vast/Dialect/HighLevel/unary-c.c, test/vast/Dialect/HighLevel/unary-d.c
This should fix #257. @kumarak could you please confirm?
=> Fix return type of high-level LNotOp

include/vast/CodeGen/FunctionInfo.hpp, include/vast/CodeGen/TypeInfo.hpp, include/vast/Translation/Types.hpp, lib/vast/CodeGen/FunctionInfo.cpp, lib/vast/CodeGen/TypeInfo.cpp, lib/vast/Translation/CodeGenTypeDriver.cpp
=> Don't drop additional type info in frontend codegen

include/vast/Translation/CodeGenStmtVisitor.hpp, test/vast/Dialect/HighLevel/constants-a.c, test/vast/Dialect/HighLevel/string-a.c
=> Fix type of string literals

include/vast/Dialect/HighLevel/HighLevelAttributes.hpp, include/vast/Dialect/HighLevel/HighLevelAttributes.td, include/vast/Dialect/HighLevel/HighLevelOps.td, lib/vast/Dialect/HighLevel/HighLevelAttributes.cpp, test/vast/Dialect/HighLevel/constants-a.c, test/vast/Dialect/HighLevel/string-a.c, test/vast/Dialect/HighLevel/string-b.c
=> Add StringLiteralAttribute

README.md
=> Add project dependencies to readme

include/vast/CodeGen/Generator.hpp, include/vast/Translation/CodeGen.hpp, include/vast/Translation/CodeGenContext.hpp, include/vast/Translation/CodeGenDriver.hpp, lib/vast/CodeGen/Generator.cpp, lib/vast/Translation/CodeGenDriver.cpp, lib/vast/Translation/FromSource.cpp, tools/vast-repl/codegen.cpp
=> Add option to add new data members to cg stack.

CMakeLists.txt, include/vast/Util/Warnings.hpp, lib/vast/Util/CMakeLists.txt, lib/vast/Util/Warnings.cpp
=> Support error reporting via exceptions

.clang-tidy, .github/workflows/install-llvm.sh, .github/workflows/linter.yml, README.md, lib/vast/Translation/CodeGenDriver.cpp, test/vast/Dialect/HighLevel/glob-front-d.c
=> Generate static global variables

include/vast/CodeGen/CodeGenBuilder.hpp, include/vast/CodeGen/CodeGenStmtVisitor.hpp, include/vast/CodeGen/CodeGenTypeVisitor.hpp, include/vast/Dialect/HighLevel/HighLevelOps.td, lib/vast/CodeGen/CodeGenTypeDriver.cpp, lib/vast/Dialect/HighLevel/HighLevelOps.cpp, test/vast/Dialect/HighLevel/calls-a.c, test/vast/Dialect/HighLevel/comma-b.c, test/vast/Dialect/HighLevel/function-void-a.c, test/vast/Dialect/HighLevel/function-void-b.c, test/vast/Dialect/HighLevel/ops-b.c, test/vast/Dialect/HighLevel/pointers-d.c, test/vast/Dialect/HighLevel/quirks-f.c, test/vast/Dialect/HighLevel/quirks-j.c
=> Make `hl` `void` function calls return `void` value

.devcontainer/devcontainer.json
- fix container docker path
- bump up llvm version to 17
=> Fix dev container

include/vast/CodeGen/CodeGenStmtVisitor.hpp
=> hl: Replace VAST_UNREACHABLE() with empty return

lib/vast/Conversion/ABI/EmitABI.cpp, lib/vast/Conversion/Common/IRsToLLVM.cpp, test/vast/Compile/SingleSource/printf-a.c, test/vast/Compile/SingleSource/printf-b.c
=> Call to functions with variadic args.

lib/vast/Conversion/FromHL/ToLLCF.cpp, test/vast/Compile/SingleSource/cf-a.c, test/vast/Compile/SingleSource/cf-b.c, test/vast/Conversion/FromHL/ToLLCF/while-a.c, test/vast/Conversion/FromHL/ToLLCF/while-b.c
Add some more tests of control flow lowering.
=> Fix bug in lowering of `while`.

include/vast/ABI/Classify.hpp, test/vast/Compile/ObjectFiles/float-a.c, test/vast/Compile/ObjectFiles/float-a.c.driver, test/vast/Compile/SingleSource/float-a.c, test/vast/Compile/SingleSource/float-b.c
Introduces basic support with some tests. Will need more testing/implementation for floats inside other types and when the count of arguments is larger - issues will be opened to track this.
=> Rudimentary support for floating point types in ABI.

.github/workflows/prerelease.yml
=> gh: Configure VAST before building docs.

docs/Tools/vast-front.md, include/vast/Frontend/Options.hpp, include/vast/Frontend/Pipelines.hpp, include/vast/Util/Common.hpp, include/vast/Util/Pipeline.hpp, include/vast/Util/Snapshots.hpp, lib/vast/Frontend/Action.cpp, lib/vast/Frontend/Consumer.cpp, lib/vast/Frontend/Pipelines.cpp, lib/vast/Util/CMakeLists.txt, lib/vast/Util/Pipeline.cpp, lib/vast/Util/Snapshots.cpp, test/vast/Conversion/enum-a.c, test/vast/Conversion/enum-b.c, test/vast/Conversion/enum-global.c, tools/vast-front/compiler_invocation.cpp
Add `emit-mlir-after=<pass-name>` option to `vast-front`.
=> Frontend option -vast-emit-mlir-after

include/vast/CodeGen/UnsupportedVisitor.hpp, include/vast/Dialect/ABI/ABIOps.td, include/vast/Dialect/Core/Func.td, include/vast/Dialect/HighLevel/HighLevelCF.td, include/vast/Dialect/HighLevel/HighLevelOps.td, include/vast/Dialect/HighLevel/HighLevelOpsCxx.td, include/vast/Dialect/HighLevel/HighLevelVar.td, include/vast/Dialect/Unsupported/UnsupportedOps.td, include/vast/Util/Common.hpp, include/vast/Util/Region.hpp, lib/vast/CodeGen/UnsupportedVisitor.cpp, lib/vast/Conversion/Core/ToLLVM.cpp, lib/vast/Dialect/ABI/ABIOps.cpp, lib/vast/Dialect/Core/CoreDialect.cpp, lib/vast/Dialect/HighLevel/HighLevelOps.cpp, lib/vast/Dialect/HighLevel/Transforms/SpliceTrailingScopes.cpp, lib/vast/Dialect/Unsupported/UnsupportedOps.cpp, lib/vast/Util/Region.cpp
- get rid of some duplicit usings `Block`, `attr_t`, `BuilderCallback`
=> Refactor some common utilities

include/vast/CodeGen/DefaultTypeVisitor.hpp, include/vast/Dialect/HighLevel/HighLevelOps.td, include/vast/Dialect/HighLevel/HighLevelTypes.td, lib/vast/CodeGen/DefaultStmtVisitor.cpp, lib/vast/CodeGen/DefaultTypeVisitor.cpp, test/vast/Dialect/HighLevel/asm-c.c, test/vast/Dialect/HighLevel/decayed-type-a.c, test/vast/Dialect/HighLevel/label-a.c, test/vast/Dialect/HighLevel/typedef-e.c, test/vast/Dialect/HighLevel/vector-a.c
=> Add various type-related fixes

include/vast/ABI/ABI.hpp, include/vast/ABI/Classify.hpp, include/vast/ABI/Driver.hpp, lib/vast/ABI/ABI.cpp, lib/vast/Conversion/ToLLVM/IRsToLLVM.cpp, test/vast/Compile/ObjectFiles/call-struct-float-a.c, test/vast/Compile/ObjectFiles/call-struct-float-a.c.driver, test/vast/Compile/ObjectFiles/call-struct-float-b.c, test/vast/Compile/ObjectFiles/call-struct-float-b.c.driver, test/vast/Compile/SingleSource/call-float-a.c, test/vast/Conversion/addressof-a.c, test/vast/Conversion/call-float-a.c, test/vast/Conversion/call-float-b.c, test/vast/Conversion/call-struct-float-a.c, test/vast/Conversion/struct-a.c, test/vast/Conversion/struct-b.c, test/vast/Conversion/struct-c.c, test/vast/Conversion/struct-d.c
Add support for more cases when floating point types are passed by value.
Add relevant tests.
Refactor some older tests related to function calls.
=> abi: Support more floating point types.

include/vast/CodeGen/CodeGenFunction.hpp, lib/vast/CodeGen/CodeGenFunction.cpp, lib/vast/CodeGen/DefaultDeclVisitor.cpp, test/vast/Dialect/HighLevel/func-a.c, test/vast/Dialect/HighLevel/func-b.c
=> Codegen function definitions if available.

lib/vast/CodeGen/CodeGenFunction.cpp, test/vast/Dialect/HighLevel/builtin_overriden.c
=> Function codegen fixes

include/vast/CodeGen/DefaultAttrVisitor.hpp, include/vast/Dialect/Core/Func.td, include/vast/Dialect/HighLevel/HighLevelAttributes.td, lib/vast/CodeGen/CodeGenFunction.cpp, lib/vast/CodeGen/DefaultAttrVisitor.cpp, test/vast/Dialect/HighLevel/func-alias.c
=> Fix crash with alias attributed functions

include/vast/CodeGen/UnsupportedVisitor.hpp, test/vast/Dialect/Unsupported/fallthrough.cpp
=> Fix hard crash in unsupported visitor (Issue 639).

include/vast/Dialect/HighLevel/HighLevelOps.td, include/vast/Dialect/HighLevel/HighLevelTypes.td, lib/vast/Dialect/HighLevel/HighLevelOps.cpp, test/vast/Dialect/HighLevel/typeof-d.c
=> Modify type verifying utils to work with typeof types

lib/vast/Conversion/FromHL/ToLLCF.cpp, test/vast/Compile/SingleSource/cf-c.c, test/vast/Compile/SingleSource/cf-d.c, test/vast/Compile/SingleSource/cf-e.c, test/vast/Compile/SingleSource/cf-f.c, test/vast/Conversion/do-while-a.c, test/vast/Conversion/do-while-b.c, test/vast/Conversion/for-a.c, test/vast/Conversion/for-b.c, test/vast/Conversion/loops-a.c, test/vast/Conversion/while-a.c, test/vast/Conversion/while-b.c
Includes some code quality improvements in the `-vast-hl-to-ll-cf` pass and some test refactors.
=> Lowering of `do-while`.

include/vast/CodeGen/ClangVisitorBase.hpp, include/vast/CodeGen/DefaultStmtVisitor.hpp, include/vast/CodeGen/DefaultVisitor.hpp, include/vast/Dialect/HighLevel/HighLevelCF.td, include/vast/Dialect/HighLevel/HighLevelOps.td, lib/vast/CodeGen/CodeGenDriver.cpp, lib/vast/CodeGen/DefaultStmtVisitor.cpp, lib/vast/CodeGen/DefaultVisitor.cpp, lib/vast/Dialect/HighLevel/HighLevelOps.cpp, test/vast/Dialect/HighLevel/binary-condop-a.c
=> Add support for GNU BinaryConditionalOperator

test/lit.cfg.py, test/vast/Dialect/HighLevel/add-a.c, test/vast/Dialect/HighLevel/arith-miamcu.c, test/vast/Dialect/HighLevel/sub-a.c
=> Run miamcu arith tests only when the feature is available.

.github/workflows/prerelease.yml
gh: Fix logic for disabling the unsupported dialect when running the Linux kernel benchmark.
=> gh: Fix logic for Linux kernel benchmark.

include/vast/Dialect/HighLevel/HighLevelOps.td, lib/vast/Dialect/HighLevel/HighLevelOps.cpp, test/vast/Dialect/HighLevel/enum-f.c
=> Add custom printer/parser combo to EnumDeclOp

include/vast/CodeGen/DefaultTypeVisitor.hpp, include/vast/Dialect/HighLevel/HighLevelTypes.td, lib/vast/CodeGen/DefaultTypeVisitor.cpp, test/vast/Dialect/HighLevel/autotype-a.c
The aim is to support the [GNU AutoType](https://www.gnu.org/software/c-intro-and-ref/manual/html_node/Auto-Type.html)
=> Add support for AutoType

.github/workflows/prerelease.yml, .github/workflows/tag_latest.yml
Also should fix improperly generated release notes
=> Bump release action version in CI

include/vast/CodeGen/DefaultTypeVisitor.hpp, include/vast/Dialect/Core/Interfaces/CMakeLists.txt, include/vast/Dialect/Core/Interfaces/DesugarTypeInterface.hpp, include/vast/Dialect/Core/Interfaces/DesugarTypeInterface.td, include/vast/Dialect/HighLevel/HighLevelTypes.hpp, include/vast/Dialect/HighLevel/HighLevelTypes.td, lib/vast/CodeGen/DefaultTypeVisitor.cpp, lib/vast/Dialect/Core/Interfaces/CMakeLists.txt, lib/vast/Dialect/Core/Interfaces/DesugarTypeInterface.cpp, lib/vast/Dialect/HighLevel/CMakeLists.txt, lib/vast/Dialect/HighLevel/HighLevelOps.cpp, test/vast/Dialect/HighLevel/counted_by-a.c, test/vast/Dialect/HighLevel/macro_qualified-a.c, test/vast/Dialect/HighLevel/paren-type-a.c
=> Add desugaring of HL types to resolve ParenType issues

include/vast/CodeGen/CodeGenDriver.hpp, lib/vast/CodeGen/CodeGenDriver.cpp, lib/vast/Tower/Tower.cpp, tools/vast-repl/command.cpp
=> tower: enable run passes on core:module using tower api
