trailofbits/vast

include/vast/Dialect/HighLevel/HighLevelOps.td, include/vast/Dialect/HighLevel/HighLevelTypes.hpp, lib/vast/Dialect/HighLevel/HighLevelOps.cpp, lib/vast/Dialect/HighLevel/HighLevelTypes.cpp, test/vast/Dialect/HighLevel/cast-b.c, test/vast/Dialect/HighLevel/pointers-e.c
- implements `getFunctionType` for typedef of function pointers. 
- updates `IndirectCallOp` to allow typedef `callee` type.
closes #171
=> Fix type assertion due to invalid cast

tools/vast-front/CMakeLists.txt, tools/vast-opt/CMakeLists.txt
Using my local build of llvm I couldn't build the project without these libraries in the CMake files.
=> Add missing libraries to linking targets

CMakeLists.txt, README.md, lib/vast/Translation/CMakeLists.txt, test/CMakeLists.txt, tools/vast-front/CMakeLists.txt, tools/vast-query/CMakeLists.txt, tools/vast-repl/CMakeLists.txt
Update vast-front linking library to use LLVMTarget instead of linking to LLVM. This is to fix build error with vcpkg.
=> Update linking library to LLVMTarget

CMakeLists.txt
PR fixes the `VAST_EXPORT_NAME` to avoid issue on case-sensitive filesystem. The issue occurs because the project name is updated to `VAST`.
=> cmake: fix vast export name

include/vast/Dialect/HighLevel/HighLevelOps.td, include/vast/Translation/CodeGenBuilder.hpp, include/vast/Translation/CodeGenStmtVisitor.hpp, include/vast/Util/Warnings.hpp, lib/vast/Dialect/HighLevel/HighLevelLinkage.cpp, lib/vast/Dialect/HighLevel/HighLevelOps.cpp, test/vast/Dialect/HighLevel/stmt-expr.c
Adds missing:
- AvailableExternalLinkageKind
- Floating point comparison operations
- GNU statement expressions
fixes #246
=> Fix csmith libraries compilation to high-level dialect

CMakeLists.txt, include/vast/Config/config.h.cmake, include/vast/Frontend/Driver.hpp, test/vast/Dialect/HighLevel/hello-world.c, tools/vast-front/driver.cpp
@lkorenc could you please test if this works on Mac? Building and running `vast-front -vast-emit-high-level test/vast/Dialect/HighLevel/hello-world.c -o -` should be enough.
=> Fix path where `vast-front` looks for includes

include/vast/Dialect/HighLevel/HighLevelOps.hpp, lib/vast/Dialect/HighLevel/HighLevelOps.cpp
As the name suggests, this PR adds a small utility function that gets the callee of a hl::CallOp.
=> Add `hl::FuncOp hl::getCallee(hl::CallOp)` utility function

include/vast/Dialect/Core/Core.td, include/vast/Dialect/LowLevel/LowLevelOps.td, include/vast/Translation/CodeGen.hpp, include/vast/Util/Triple.hpp, lib/vast/Conversion/Common/LLCFToLLVM.hpp, test/vast/Compile/SingleSource/fib-a.c, test/vast/Conversion/FromHL/ToLLCF/for-a.c, test/vast/Conversion/FromHL/ToLLCF/for-b.c, test/vast/Conversion/FromHL/ToLLVars/vars-a.c
A minor PR with smaller fixes
* Adds `target_triple` attribute to top level `mlir::ModuleOp` VAST works with (and then lowers it to the `llvm::Module` if conversion happens)
* Add `assemblyFormat` to various `ll` operations that did not have it
* Update tests and attempt to introduce recompilation tests
=> Improvements to lower dialects

include/vast/Translation/CodeGen.hpp, include/vast/Translation/CodeGenTypeDriver.hpp, lib/vast/CodeGen/TypeInfo.cpp, lib/vast/Translation/CodeGenTypeDriver.cpp, test/vast/Dialect/HighLevel/fun-type-a.c
- Extract types from ParenType when needed
- Make argument types `lvalue`s
=> Fix errors/bugs in `vast-front` function types

include/vast/Translation/CodeGenStmtVisitor.hpp, test/vast/Dialect/HighLevel/array-d.c, test/vast/Dialect/HighLevel/pointers-c.c, test/vast/Dialect/HighLevel/string-a.c, test/vast/Dialect/HighLevel/string-b.c
According to the C standard the result of array to ptr decay is not an lvalue.
=> Make array to ptr decay strip `lvalue` from type

include/vast/Conversion/Common/Rewriter.hpp, include/vast/Dialect/HighLevel/HighLevelCF.td, include/vast/Dialect/HighLevel/HighLevelTypes.td, include/vast/Util/LLVMTypeConverter.hpp, lib/vast/Conversion/Common/Common.hpp, lib/vast/Conversion/Common/IRsToLLVM.cpp, lib/vast/Conversion/Common/LLCFToLLVM.hpp, lib/vast/Conversion/FromHL/EmitLazyRegions.cpp, lib/vast/Conversion/FromHL/ToLLCF.cpp, lib/vast/Conversion/FromHL/ToLLVars.cpp, lib/vast/Dialect/HighLevel/Transforms/HLLowerTypes.cpp, lib/vast/Frontend/GenAction.cpp, lib/vast/Target/LLVMIR/Convert.cpp, test/vast/Compile/SingleSource/argc.c, test/vast/Compile/SingleSource/argv-a.c, test/vast/Compile/SingleSource/global-a.c, test/vast/Compile/SingleSource/label-a.c, test/vast/Compile/SingleSource/putchar-a.c, test/vast/Compile/SingleSource/puts-a.c, test/vast/Compile/SingleSource/strlit-a.c
Improve lowering to llvm
* string literals
* global variables (these are now also ignored by `hl-to-ll-vars` pass
* scope-like operations (scope, labels)
Fixes `vast-front` not running scope splicing when compiling.
`vast-front` should now print better debug info when some conversion pass fails.
=> Various lowering improvements

.github/workflows/build.yml
Due to #185 we are not able to test GCC build at the moment.
=> Turn off unsupported gcc.

.github/workflows/linter.yml, include/vast/Translation/CodeGen.hpp, lib/vast/Translation/CodeGenTypeDriver.cpp
Add lvalue manually at the end instead of using special visitor because of type cache hits.
=> Fix function argument lvalue addition.

include/vast/Translation/CodeGenStmtVisitor.hpp, test/vast/Dialect/HighLevel/fun-ref-a.c
Make FunDeclRefExpr visitor lazily emit forward declared functions.
=> FunDeclRef lazy emit of forward declarations

include/vast/Conversion/Common/Rewriter.hpp, include/vast/Dialect/HighLevel/HighLevelTypes.hpp, include/vast/Dialect/HighLevel/HighLevelUtils.hpp, include/vast/Dialect/LowLevel/LowLevelOps.td, include/vast/Util/TypeUtils.hpp, lib/vast/Conversion/FromHL/StructsToLLVM.cpp, lib/vast/Conversion/FromHL/ToLLGEPs.cpp, lib/vast/Dialect/HighLevel/HighLevelTypes.cpp
Introduce a bunch of utilities for working with records. These were before randomly re-implemented in a bunch of conversions. So far I am keeping them header only as I suspect we will need to eventually change some concerte `hl::` types to templates anyway to support C++ as well.
PR also includes refactor of some of our more in-progress passes to use this newer api.
There is one sneaky `ll` commit that adds `Extract` and `Concat` operations which will be needed by abi lowering.
=> Add header with some hl utilities

.gitignore, include/vast/CMakeLists.txt, include/vast/Conversion/Passes.td, include/vast/Tower/CMakeLists.txt, include/vast/Tower/Tower.hpp, include/vast/repl/command.hpp, include/vast/repl/state.hpp, lib/vast/CMakeLists.txt, lib/vast/Tower/CMakeLists.txt, lib/vast/Tower/Tower.cpp, test/lit.cfg.py, test/repl/apply.c, test/repl/raise.c, tools/vast-repl/command.cpp, tools/vast-repl/vast-repl.cpp
The `tower` component provides an API for applying passes while maintaining a history with provenance information for every operation. This is done by propagating `mlir::Operation *` of the old operation to the new operation via `mlir::FusedLoc` and `mlir::OpaqueLoc`.
=> Initial prototype of the `tower` component.

include/vast/CodeGen/CodeGenStmtVisitor.hpp, lib/vast/Dialect/Unsupported/UnsupportedOps.cpp
Changelog:
- Emit an error if the Var decl is not present in the lookup table. During code generation,  while lowering `DeclRefExpr`, it searches for the declaration in the lookup table that may not be present. This situation could arise if the Decl node is not visited before. A potential solution could be visiting the Decl node if it is not present in the lookup table.
- Check for the null result type before setting the type in Unsupported Stmt Dialect
=> Add check for the decl in lookup table

include/vast/CodeGen/CodeGenBuilder.hpp, include/vast/CodeGen/CodeGenContext.hpp, include/vast/CodeGen/CodeGenDeclVisitor.hpp, include/vast/CodeGen/CodeGenStmtVisitor.hpp, include/vast/Dialect/Core/Core.td, include/vast/Dialect/Core/CoreOps.td, include/vast/Dialect/HighLevel/HighLevelOps.td, include/vast/Util/Scopes.hpp, lib/vast/Conversion/Common/IRsToLLVM.cpp, lib/vast/Dialect/Core/CoreOps.cpp, lib/vast/Dialect/HighLevel/HighLevelOps.cpp, lib/vast/Dialect/HighLevel/Transforms/SpliceTrailingScopes.cpp, test/vast/Conversion/FromHL/ToLLCF/for-b.c, test/vast/Dialect/HighLevel/loop-a.cpp, test/vast/Dialect/HighLevel/quirks-m.cpp, test/vast/Dialect/HighLevel/scope-a.c, test/vast/Dialect/HighLevel/switch-b.c, test/vast/Dialect/HighLevel/vars-c.c, test/vast/Transform/FromHL/LowerTypes/scope-a.c
As `ScopeOp` doesn't map to any `AST` member we should move it out of `hl` dialect.
=> Move `ScopeOp` from `HighLevel` to `Core` dialect

lib/vast/Conversion/Common/IRsToLLVM.cpp, test/vast/Conversion/Common/IRsToLLVM/sizeof-a.c
Implement `sizeof(type)` conversion for primitive types.
=> Sizeof lowering

include/vast/Frontend/FrontendAction.hpp, include/vast/Frontend/GenAction.hpp, lib/vast/Frontend/GenAction.cpp, test/vast/Dialect/HighLevel/glob-front-a.c, test/vast/Dialect/HighLevel/glob-front-b.c, test/vast/Dialect/HighLevel/glob-front-c.c, test/vast/Dialect/HighLevel/hello-world.c, tools/vast-front/compiler_invocation.cpp
Replaces specific options `-vast-emit-high-level` and `-vast-emit-cir` with generic `-vast-emit-mlir=...`.
=> Generalize emit mlir options and remove duplicits.

include/vast/CodeGen/CodeGenAttrVisitor.hpp, include/vast/CodeGen/CodeGenDeclVisitor.hpp, include/vast/CodeGen/UnreachableVisitor.hpp, include/vast/CodeGen/Util.hpp, include/vast/Dialect/Core/Linkage.td, include/vast/Dialect/HighLevel/HighLevelAttributes.td, include/vast/Util/TypeList.hpp, lib/vast/Dialect/Core/Linkage.cpp, test/vast/Dialect/HighLevel/attr-c.c, test/vast/Dialect/HighLevel/attr-d.c
- support for additional attributes (I covered all attributes that are used for `malloc` in `stdlib`)
- deduplication of attributes - I believe this shouldn't be necessary, but it might be a bug in the AST…
=> Attribute visitor improvements

include/vast/Dialect/ABI/ABI.td, include/vast/Dialect/ABI/ABIOps.hpp, include/vast/Dialect/Core/Func.hpp, include/vast/Dialect/Core/Func.td, include/vast/Dialect/HighLevel/HighLevel.td, include/vast/Dialect/HighLevel/HighLevelOps.td, include/vast/Dialect/LowLevel/LowLevel.td, lib/vast/Dialect/ABI/ABIOps.cpp, lib/vast/Dialect/Core/CMakeLists.txt, lib/vast/Dialect/Core/Func.cpp, lib/vast/Dialect/HighLevel/HighLevelOps.cpp, lib/vast/Dialect/LowLevel/LowLevelOps.cpp
Not sure how to avoid the stubs that forward to their `core::` counterparts as I was not able to specify `custom< core::XXX >` in the `assemblyFormat`. One option would be to import `Core/Func.hpp` and then just `using namespace vast::core` but it sounds like more pain than gain.
=> Unify various copy & paste utilities of `FuncOp`s.

lib/vast/Conversion/Common/IRsToLLVM.cpp, lib/vast/Conversion/Core/ToLLVM.cpp, test/vast/Conversion/Common/IRsToLLVM/bin_chain-a.c
=> Fix conversion of chained logical operators

include/vast/Util/Warnings.hpp
=> util: Clean up and fix UB in `VAST_[CHECK,ASSERT,UNREACHABLE]` macros.

CMakePresets.json, cmake/AddVAST.cmake, include/vast/Frontend/Options.hpp, include/vast/Frontend/Pipelines.hpp, include/vast/Util/Pipeline.hpp, lib/vast/Conversion/ABI/Passes.cpp, lib/vast/Conversion/Core/Passes.cpp, lib/vast/Conversion/FromHL/Passes.cpp, lib/vast/Dialect/HighLevel/Passes.cpp, lib/vast/Frontend/Consumer.cpp, lib/vast/Frontend/Options.cpp, lib/vast/Frontend/Pipelines.cpp, lib/vast/Util/Pipeline.cpp
Introduces set of options  `-vast-disable-<pipeline-name>` which allow the user to turn off specific steps of pipeline.
Adds capability to name pipelines and rename passes.
=> Allow to disable pipelines by name.

include/vast/Conversion/ABI/Common.hpp, lib/vast/Conversion/ABI/EmitABI.cpp, lib/vast/Conversion/ABI/LowerABI.cpp, lib/vast/Conversion/FromHL/ToLLCF.cpp, test/vast/Compile/SingleSource/putchar-a.c, test/vast/Compile/SingleSource/puts-a.c
closes #376 and fixes incorrect name prefix during abi conversions.
=> Fix minor issues in ABI conversions.

lib/vast/Conversion/Common/Common.hpp, lib/vast/Conversion/Common/IRsToLLVM.cpp, lib/vast/Conversion/Common/LLCFToLLVM.hpp, test/vast/Compile/SingleSource/array-a.c, test/vast/Compile/SingleSource/array-b.c, test/vast/Compile/SingleSource/array-c.c, test/vast/Compile/SingleSource/array-d.c, test/vast/Compile/SingleSource/array-e.c, test/vast/Compile/SingleSource/struct-a.c, test/vast/Compile/SingleSource/struct-b.c, test/vast/Conversion/Common/IRsToLLVM/cmake-platform-test.c
```
#include <stdint.h>
#undef KEY
#if defined(__i386)
#elif defined(__x86_64)
#elif defined(__PPC64__)
#elif defined(__ppc64__)
#elif defined(__PPC__)
#elif defined(__ppc__)
#elif defined(__aarch64__)
#elif defined(__ARM_ARCH_7A__)
#elif defined(__ARM_ARCH_7S__)
#endif
#define SIZE (sizeof(unsigned short))
static char info_size[] =  {'I', 'N', 'F', 'O', ':', 's','i','z','e','[',
('0' + ((SIZE / 10000)%10)),
('0' + ((SIZE / 1000)%10)),
('0' + ((SIZE / 100)%10)),
('0' + ((SIZE / 10)%10)),
('0' +  (SIZE    % 10)),
']',
#ifdef KEY
' ','k','e','y','[', KEY, ']',
#endif
'\0'};
#ifdef __CLASSIC_C__
int main(argc, argv) int argc; char *argv[];
#else
int main(int argc, char *argv[])
#endif
{
int require = 0;
require += info_size[argc];
(void)argv;
return require;
}
```
=> Fix lowering of global variables to llvm

include/vast/Conversion/TypeConverters/LLVMTypeConverter.hpp, include/vast/Conversion/TypeConverters/TypeConverter.hpp, include/vast/Dialect/HighLevel/HighLevelOps.hpp, include/vast/Dialect/HighLevel/HighLevelOps.td, include/vast/Dialect/HighLevel/HighLevelUtils.hpp, include/vast/Interfaces/AggregateTypeDefinitionInterface.hpp, include/vast/Interfaces/AggregateTypeDefinitionInterface.td, include/vast/Interfaces/CMakeLists.txt, include/vast/Interfaces/SymbolInterface.td, lib/vast/Conversion/Common/IRsToLLVM.cpp, lib/vast/Conversion/FromHL/ToLLGEPs.cpp, lib/vast/Dialect/HighLevel/HighLevelOps.cpp, lib/vast/Interfaces/AggregateTypeDefinitionInterface.cpp, lib/vast/Interfaces/CMakeLists.txt, test/vast/Compile/SingleSource/nested-struct-a.c, test/vast/Compile/SingleSource/nested-union-a.c, test/vast/Compile/SingleSource/nested-union-b.c, test/vast/Compile/SingleSource/union-a.c, test/vast/Compile/SingleSource/union-b.c, test/vast/Compile/SingleSource/union-c.c, test/vast/Compile/SingleSource/union-d.c
Add basic lowering of unions - this required some improvements to api that facilitates walking of aggregate types.
* handle lowering unions
* handle lowering of nested structures
* `StructDeclOp` and `UnionDecl` op now implement `AggregateTypeDefinitionInterface`
closes #500
=> Union lowering

include/vast/CodeGen/CodeGenStmtVisitor.hpp, lib/vast/Dialect/HighLevel/HighLevelTypes.cpp
- Change each `getFunctionType()` overload to return an optional `FunctionType` so that they can return an empty option if they fail instead of crashing VAST.
- Check the return value of `getFunctionType()` in `VisitIndirectCall()` and return an `IndirectCallOp` only if the return value is not an empty option. Otherwise, return an empty op for a fallback visitor (e.g., the unsupported visitor) to handle.
=> Change getFunctionType() to return an optional

.github/workflows/llvm-ts-run.yml, .github/workflows/prerelease.yml, README.md, docs/GettingStarted/extend.md, docs/Projects/related.md, docs/README.md, docs/Tools/vast-front.md, www/mkdocs.yml, www/setup.sh
- add links to compiler explorer
- describes `vast-front` options
- fixes typos
=> Extend readme and vast-front docs

lib/vast/Conversion/ABI/EmitABI.cpp, test/vast/Conversion/ABI/direct-a.c, test/vast/Conversion/ABI/direct-merge-a.c, test/vast/Conversion/ABI/direct-nested-a.c, test/vast/Conversion/ABI/direct-overlap-a.c
This is a temporary fix as it will be updated more once lowering of value categories is merged.
=> Fix types of `abi.yield`.

.github/workflows/build.yml, .github/workflows/linter.yml, .github/workflows/llvm-ts-run.yml, .github/workflows/prerelease.yml, CMakePresets.json, docs/GettingStarted/build.md, scripts/setup_llvm_dependencies.sh
- adds `ci` specific preset
- adds `compiler-explorer` specific preset
- renames `ninja-multi-default` to `default` preset
- adds script to setup `compiler-explorer` docker
=> CMake presets refactor

.github/workflows/prerelease.yml
Trying to see if this provides a meaningful speedup for sv-comp benchmarks. I have also disabled compiler crash diagnostics in the SV-Comp repository (only on the CI branch at the moment).
Could potentially lead to re-enabling of `llvm` as a target for SV-Comp
=> Disable LLVM symbolizer in prerelease CI.

include/vast/CodeGen/CodeGenOptions.hpp, include/vast/Frontend/Options.hpp, lib/vast/CodeGen/CodeGenDriver.cpp
Adds `-vast-disable-unsupported` option to detect errors more quickly.
=> Disable unsupported dialect

.github/workflows/prerelease.yml
This also requires some modification to the benchmark runners themselves.
=> Add runs without unsupported dialect to CI

include/vast/Conversion/TypeConverters/HLToStd.hpp, include/vast/Conversion/TypeConverters/LLVMTypeConverter.hpp, test/vast/Compile/ObjectFiles/call-array-a.c, test/vast/Compile/ObjectFiles/call-array-a.c.driver, test/vast/Compile/SingleSource/union-e.c, test/vast/Conversion/subscript-a.c, test/vast/Conversion/subscript-b.c, test/vast/Transform/HL/LowerTypes/array-a.c, test/vast/Transform/HL/LowerTypes/array-b.c, test/vast/Transform/HL/LowerTypes/strlit-a.c, test/vast/Transform/HL/LowerTypes/vars-b.cpp
There is a bunch of problems with `memref` in the pipeline - most notably it not being easily added to data layout. Apart from that, it is also kind of weird that `struct/pointer` survive all the way down to final `ll`, whereas `array` did not - with this change it is more uniform.
=> No longer lower `hl.array` into `memref`.

include/vast/CodeGen/CodeGenVisitorBase.hpp, include/vast/CodeGen/CodeGenVisitorList.hpp, include/vast/CodeGen/DefaultVisitor.hpp, include/vast/CodeGen/UnreachableVisitor.hpp, include/vast/CodeGen/UnsupportedVisitor.hpp, include/vast/Util/Common.hpp, lib/vast/CodeGen/AttrVisitorProxy.cpp, lib/vast/CodeGen/CodeGenVisitorBase.cpp, lib/vast/CodeGen/DefaultVisitor.cpp
Changes visitor API to provide:
```
std::optional< named_attr > visit(const clang_attr *, scope_context &scope);
```
instead of
```
mlir_attr visit(const clang_attr *, scope_context &scope);
```
This allows visitors to take care of responsibility for attribute naming, and does not leak this abstraction to top-level visitors.
=> Allow visitors specify attribute names

include/vast/Frontend/Action.hpp, include/vast/repl/cli.hpp, include/vast/repl/codegen.hpp, include/vast/repl/command.hpp, include/vast/repl/command_base.hpp, include/vast/repl/common.hpp, include/vast/repl/config.hpp, include/vast/repl/pipeline.hpp, include/vast/repl/state.hpp, lib/vast/Frontend/Action.cpp, test/repl/raise.c, tools/vast-repl/CMakeLists.txt, tools/vast-repl/cli.cpp, tools/vast-repl/codegen.cpp, tools/vast-repl/command.cpp, tools/vast-repl/config.cpp, tools/vast-repl/vast-repl.cpp
Update `vast-repl` to use newer APIs.
Backport some forgotten patches in the experimental branches - some of these features do not work yet, but there is no reason not to include them as we are already developing `tower` and we will need them in some form eventually.
=> Bring `vast-repl` up to date.

include/vast/CodeGen/CodeGenBuilder.hpp, include/vast/CodeGen/DefaultDeclVisitor.hpp, include/vast/CodeGen/DefaultStmtVisitor.hpp, include/vast/CodeGen/DefaultTypeVisitor.hpp, include/vast/CodeGen/UnsupportedVisitor.hpp, include/vast/Dialect/HighLevel/HighLevelTypes.td, lib/vast/CodeGen/DefaultDeclVisitor.cpp, lib/vast/CodeGen/DefaultStmtVisitor.cpp, lib/vast/CodeGen/DefaultTypeVisitor.cpp, test/vast/Dialect/HighLevel/atomic-a.c, test/vast/Dialect/HighLevel/atomic-b.c, test/vast/Dialect/HighLevel/stdatomic-a.c
- adds `hl.atomic< type >` type definition
- allows to create `AtomicToNonAtomic` and `NonAtomicToAtomic` casts
- fixes validity check in monadic builder
=> High-level support for _Atomic type and its casts

include/vast/Dialect/HighLevel/HighLevelCF.td, include/vast/Dialect/HighLevel/HighLevelOps.td, lib/vast/CodeGen/DefaultStmtVisitor.cpp, test/vast/Dialect/HighLevel/fun-ptr-a.c, test/vast/Dialect/HighLevel/fun-ptr-b.c, test/vast/Dialect/HighLevel/pointers-d.c, test/vast/Dialect/HighLevel/pointers-e.c, test/vast/Dialect/HighLevel/pointers-f.c, test/vast/Dialect/HighLevel/quirks-j.c, test/vast/Dialect/HighLevel/ternary-a.c
I have also made a small change to `condop` type for the sake of readability and testability.
=> Fixup function pointer lvalues

docs/Tools/vast-front.md, include/vast/Dialect/HighLevel/HighLevelTypes.td, include/vast/Frontend/Options.hpp, lib/vast/Frontend/Pipelines.cpp, test/vast/Dialect/HighLevel/typeof-d.c
Fix #645 
I have also fixed the `-vast-disable-verifier` option (renamed form `vast-disable-vast-verifier`), so that it also applies to passes - since even emitting `hl` requires us to run a pass, it was virtually useless
=> Fix type verification when TypeOf type is involved

include/vast/Dialect/HighLevel/HighLevelTypes.td, test/vast/Dialect/HighLevel/subscript-a.c
=> Fix array subscript operator when an enum typed variable is used

include/vast/repl/command.hpp, tools/vast-repl/command.cpp
Add a template for running clang static analysis in vast-repl.
=> Allow vast-repl to run Clang static analyses.

.github/workflows/prerelease.yml, www/mkdocs.yml, www/setup.sh
Add steps to download, configure, and build the Linux kernel; run vast-front on its compilation units; and tabulate the results.
=> Add steps to run vast-front on Linux kernel

include/vast/Dialect/Core/Func.hpp, lib/vast/Dialect/Core/Func.cpp, test/vast/Dialect/HighLevel/linkage-a.c
Cases when function declaration (without definition) has an unknown linkage are valid because of `inline` specified declarations.
=> Fix function linkage verifier

.github/workflows/prerelease.yml
- Generate Linux compile commands with the `gen_compile_commands.py` script instead of using `bear` to do so since `bear`'s output does not handle single quotes in command-line macro definitions.
- Add `make prepare` step when building the Linux kernel.
- Checkout Linux v6.10 specifically to improve reproducibility.
=> Generate Linux compile commands, don't intercept with bear

docs/GettingStarted/integration.md, include/vast/CodeGen/CodeGenFunction.hpp, include/vast/CodeGen/CodeGenPolicy.hpp, include/vast/CodeGen/DefaultCodeGenPolicy.hpp, include/vast/CodeGen/DefaultDeclVisitor.hpp, include/vast/CodeGen/DefaultVisitor.hpp, lib/vast/CodeGen/CodeGenDriver.cpp, lib/vast/CodeGen/CodeGenFunction.cpp, lib/vast/CodeGen/DefaultDeclVisitor.cpp, lib/vast/CodeGen/DefaultVisitor.cpp
- Combines the driver options `emit_strict_function_return` and `missing_return_policy` into a single virtual class, `policy_base`, with methods for obtaining these values on a per-functiondecl basis.
- Replaces all uses of the policy options with the new policy class.
- Adds a new policy option, `skip_function_body`, for controlling whether to emit the body of a given function decl.
- Adds a new policy option, `skip_global_initializer`, for controlling whether to emit the body of a given var decl.
- Adds a `default_policy` class to provide default policy options. It accepts a `vast::cc::action_options &` instance in its constructor and defaults to returning the options' settings for all function decls.
Addresses the first two checkboxes of #462
=> Add codegen policy

include/vast/CodeGen/InvalidMetaGenerator.hpp, include/vast/CodeGen/UnsupportedVisitor.hpp, lib/vast/CodeGen/CodeGenDriver.cpp
- Adds a metagenerator to the unsupported visitor so that clients can choose what locations are emitted for unsupported operations.
- Adds an `invalid_meta_gen` struct to only emit unknown locations, and pass it to the unsupported visitor in vast's default visitor stack.
Closes #690
=> Add metagen to unsupported visitor

include/vast/Dialect/HighLevel/HighLevelCF.td, lib/vast/CodeGen/DefaultStmtVisitor.cpp, lib/vast/Conversion/ToLLVM/IRsToLLVM.cpp
Changes `hl.skip` to `hl.null` to mirror clang naming.
=> Replace SkipStmt with NullStmt.

include/vast/CodeGen/CodeGenPolicy.hpp, include/vast/CodeGen/DefaultCodeGenPolicy.hpp, include/vast/Dialect/Core/Linkage.hpp, lib/vast/CodeGen/DefaultDeclVisitor.cpp, lib/vast/Dialect/Core/Linkage.cpp, test/vast/Dialect/HighLevel/array-a.c, test/vast/Dialect/HighLevel/cast-b.c, test/vast/Dialect/HighLevel/enum-a.c, test/vast/Dialect/HighLevel/glob-linkage-a.c, test/vast/Dialect/HighLevel/pointers-b.c, test/vast/Dialect/HighLevel/qualifiers-e.c, test/vast/Dialect/HighLevel/qualifiers-g.c, test/vast/Dialect/HighLevel/qualifiers-h.c, test/vast/Dialect/HighLevel/qualifiers-i.c, test/vast/Dialect/HighLevel/qualifiers-j.c, test/vast/Dialect/HighLevel/quirks-n.c, test/vast/Dialect/HighLevel/storage-a.c, test/vast/Dialect/HighLevel/struct-a.c, test/vast/Dialect/HighLevel/struct-c.c, test/vast/Dialect/HighLevel/struct-f.c, test/vast/Dialect/HighLevel/union-a.c, test/vast/Dialect/HighLevel/union-b.c, test/vast/Transform/HL/LowerTypes/array-a.c
=> Fix common linkage

include/vast/Dialect/HighLevel/HighLevelVar.td, lib/vast/CodeGen/DefaultDeclVisitor.cpp, lib/vast/Conversion/ToLLVM/IRsToLLVM.cpp, lib/vast/Conversion/ToMem/EvictStaticLocals.cpp, lib/vast/Dialect/HighLevel/HighLevelOps.cpp, test/vast/Conversion/static-var-b.c, test/vast/Conversion/zero-init-a.c, test/vast/Dialect/HighLevel/array-a.c, test/vast/Dialect/HighLevel/array-c.c, test/vast/Dialect/HighLevel/autotype-a.c, test/vast/Dialect/HighLevel/constants-a.c, test/vast/Dialect/HighLevel/literals-a.c, test/vast/Dialect/HighLevel/pointers-a.c, test/vast/Dialect/HighLevel/pointers-b.c, test/vast/Dialect/HighLevel/qualifiers-a.cpp, test/vast/Dialect/HighLevel/qualifiers-e.c, test/vast/Dialect/HighLevel/qualifiers-h.c, test/vast/Dialect/HighLevel/qualifiers-i.c, test/vast/Dialect/HighLevel/quirks-j.c, test/vast/Dialect/HighLevel/quirks-n.c, test/vast/Dialect/HighLevel/typeof-b.c, test/vast/Dialect/HighLevel/typeof-c.c, test/vast/Transform/HL/LowerTypes/array-a.c, test/vast/Transform/HL/LowerTypes/vars-c.c
- Add const to hl vardecl and propagate it to llvm globals
- Zero init variables with static storage duration, if they do not have initializer
=> Improve global variable lowering

CMakeLists.txt, tools/vast-front/CMakeLists.txt
Some Linux distributions (i.e. NixOS) install LLVM, MLIR, and clang in different prefixes. On these distributions, variables like `LLVM_INCLUDE_DIRS` and `MLIR_INCLUDE_DIRS` have different values. These changes handle a few instances of this issue to get VAST building on NixOS and Nix on Darwin.
=> cmake: handle separate prefix for LLVM/MLIR/clang

include/vast/Dialect/HighLevel/HighLevelVar.td
=> hl: Remove empty else assembly form of constant attribute from VarDeclOp.

include/vast/Dialect/Core/CommonAttrConstraints.td, include/vast/Dialect/Core/CoreAttributes.hpp, include/vast/Dialect/Core/SymbolTable.hpp, include/vast/Dialect/HighLevel/HighLevelAttributes.td, include/vast/Dialect/HighLevel/HighLevelOps.td, lib/vast/Dialect/Core/CoreAttributes.cpp, lib/vast/Dialect/Core/SymbolTable.cpp, tools/vast-query/vast-query.cpp
- adds typed references
- implements type aware symbol resolution
=> Introduce typed symbol references

include/vast/Dialect/Parser/Ops.td, lib/vast/Conversion/Parser/ToParser.cpp
This operation is to denote places where we are not able to determine 
whether the operation is parsing or not just from local analysis.
This is to be refined in future passes or can be used as overapproximation of parser.
=> Introduce maybe parse op

include/vast/Conversion/Parser/Passes.hpp, include/vast/Conversion/Parser/Passes.td, include/vast/Dialect/Parser/Ops.td, lib/vast/Conversion/Parser/CMakeLists.txt, lib/vast/Conversion/Parser/ReconcileCasts.cpp, lib/vast/Conversion/Parser/ToParser.cpp, lib/vast/Conversion/Parser/Utils.hpp, lib/vast/Dialect/Parser/Ops.cpp
- adds `-vast-parser-reconcile-casts` pass to eliminate intermediate unrealized casts to pr.cast
- adds simple folds for parse operations
=> Reconcile unrealized parser casts to pr.cast
